### ISSUE TITLE
Fable.Elmish.Browser broken after Fable.Browser.Dom update

### ISSUE THREAD

**Issue by forki** [fable-elmish/browser#34]
I did the following paket update:

![image](https://user-images.githubusercontent.com/57396/90730642-c08ca200-e2c8-11ea-90fa-dd396b994df7.png)

which leads to:

     /home/gitlab-runner/builds/e76ee70f/0/products/eCarApp/.fable/Fable.Elmish.Browser.3.0.4/navigation.fs(70,13): (70,67) error FSHARP: A unique overload for method 'addEventListener' could not be determined based on type information prior to this program point. A type annotation may be needed.
     Known types of arguments: string * 'a
     Candidates:
      - abstract member EventTarget.addEventListener : type:string * listener:(Event -> unit) * ?options:AddEventListenerOptions -> unit
      - abstract member EventTarget.addEventListener : type:string * listener:(Event -> unit) * ?useCapture:bool -> unit (code 41)
      @ ./src/Client/App.fs 6:0-143 19:15-54
      @ ./src/Client/Client.fsproj
      @ multi whatwg-fetch @babel/polyfill ./src/Client/Client.fsproj ./src/Client/index.js

**Comment by MangelMaxime** [comment]
I just released Fable.Browser.Event version 1.2.0 which should fix the problem.

The problem is coming because we added a new overload but both candidates have the third argument as optional so F# can't decide which one to use. I added a new overload without the third argument to force F# compiler to decide.

Please re-open if the fix didn't work.

**Comment by forki** [comment]
thank you!
